import os
import math
import numpy as np
from PIL import Image

from libero.libero import benchmark, get_libero_path
from libero.libero.envs import OffScreenRenderEnv


# =============================================================
# Save PLY point cloud
# =============================================================
def save_point_cloud_ply(points, path):
    header = (
        "ply\nformat ascii 1.0\n"
        "comment generated by export_gt_pointcloud_final.py\n"
        f"element vertex {len(points)}\n"
        "property float x\nproperty float y\nproperty float z\n"
        "end_header\n"
    )
    with open(path, "w") as f:
        f.write(header)
        np.savetxt(f, points, fmt="%.6f")


# =============================================================
# Extract mesh geometry in world coordinates
# =============================================================
def geom_mesh_in_world(sim, geom_id):
    model, data = sim.model, sim.data
    mesh_id = model.geom_dataid[geom_id]

    if mesh_id < 0:
        return None

    v_start = model.mesh_vertadr[mesh_id]
    v_count = model.mesh_vertnum[mesh_id]
    f_start = model.mesh_faceadr[mesh_id]
    f_count = model.mesh_facenum[mesh_id]

    verts_local = model.mesh_vert[v_start:v_start + v_count]
    faces = model.mesh_face[f_start:f_start + f_count]

    # transform → world
    R = data.geom_xmat[geom_id].reshape(3, 3)
    t = data.geom_xpos[geom_id]
    verts_world = verts_local @ R.T + t

    return verts_world, faces


# =============================================================
# Collect all meshes
# =============================================================
def collect_world_meshes(env):
    meshes = []
    sim, model = env.sim, env.sim.model

    for geom_id in range(model.ngeom):
        m = geom_mesh_in_world(sim, geom_id)
        if m is None:
            continue

        body_id = model.geom_bodyid[geom_id]
        name = model.body_id2name(body_id)

        meshes.append({
            "name": f"{name}_geom{geom_id}",
            "verts": m[0],
            "faces": m[1],
        })
    return meshes


# =============================================================
# Sample uniformly across mesh triangles
# =============================================================
def sample_points_on_mesh(verts, faces, n_samples):
    tri = verts[faces]  # shape (F,3,3)

    # triangle areas
    areas = 0.5 * np.linalg.norm(
        np.cross(tri[:, 1] - tri[:, 0], tri[:, 2] - tri[:, 0]),
        axis=1
    )
    probs = areas / areas.sum()

    face_idx = np.random.choice(len(faces), size=n_samples, p=probs)
    tri_sel = tri[face_idx]

    r1 = np.sqrt(np.random.rand(n_samples, 1))
    r2 = np.random.rand(n_samples, 1)

    pts = (
        tri_sel[:, 0]
        + r1 * (tri_sel[:, 1] - tri_sel[:, 0])
        + r2 * (tri_sel[:, 2] - tri_sel[:, 0])
    )
    return pts


def sample_points_from_meshes(meshes, pts_per_mesh=6000):
    pts = [sample_points_on_mesh(m["verts"], m["faces"], pts_per_mesh)
           for m in meshes]
    return np.concatenate(pts, axis=0)


# =============================================================
# MuJoCo camera parameters (correct version)
# =============================================================
def get_camera_params(sim, camera_name, width, height):
    cam_id = sim.model.camera_name2id(camera_name)

    # intrinsics
    fovy = sim.model.cam_fovy[cam_id]
    fy = 0.5 * height / math.tan(0.5 * np.deg2rad(fovy))
    fx = fy * width / height
    cx = (width - 1) / 2.0
    cy = (height - 1) / 2.0

    # extrinsics: MuJoCo stores cam_xmat as camera→world
    R_c2w = sim.data.cam_xmat[cam_id].reshape(3, 3)
    t_w   = sim.data.cam_xpos[cam_id]

    # LIBERO/MuJoCo uses global near/far for all cameras
    near = sim.model.vis.map.znear
    far  = sim.model.vis.map.zfar

    return {
        "fx": fx, "fy": fy,
        "cx": cx, "cy": cy,
        "R_c2w": R_c2w,   # camera → world
        "t_w": t_w,
        "near": near,
        "far": far,
    }


# =============================================================
# World → Camera → Frustum Crop
# =============================================================
def crop_points_by_camera(points_world, cam_params, img_w, img_h):
    if len(points_world) == 0:
        return np.zeros((0, 3))

    R_c2w = cam_params["R_c2w"]
    t_w = cam_params["t_w"]
    R_w2c = R_c2w.T  # invert rotation

    # world → camera
    pts_cam = (points_world - t_w) @ R_w2c

    x = pts_cam[:, 0]
    y = pts_cam[:, 1]
    z = pts_cam[:, 2]  # MuJoCo: +Z is forward

    # depth clipping
    near, far = cam_params["near"], cam_params["far"]
    valid = (z > near) & (z < far)

    if not np.any(valid):
        return np.zeros((0, 3))

    x = x[valid]
    y = y[valid]
    z = z[valid]

    # project
    u = cam_params["fx"] * (x / z) + cam_params["cx"]
    v = cam_params["fy"] * (y / z) + cam_params["cy"]

    in_view = (u >= 0) & (u < img_w) & (v >= 0) & (v < img_h)

    if not np.any(in_view):
        return np.zeros((0, 3))

    return np.stack([x[in_view], y[in_view], z[in_view]], axis=-1)


# =============================================================
# Main
# =============================================================
def main():
    # ===== Load LIBERO task =====
    benchmark_dict = benchmark.get_benchmark_dict()
    task_suite = benchmark_dict["libero_spatial"]()
    task = task_suite.get_task(0)

    bddl_file = os.path.join(
        get_libero_path("bddl_files"),
        task.problem_folder,
        task.bddl_file
    )

    camera_names = ["agentview", "robot0_eye_in_hand"]

    env = OffScreenRenderEnv(
        bddl_file_name=bddl_file,
        camera_heights=128,
        camera_widths=128,
        camera_names=camera_names,
        camera_depths=False
    )
    env.seed(0)
    env.reset()

    init_states = task_suite.get_task_init_states(0)
    env.set_init_state(init_states[0])

    os.makedirs("gt_meshes", exist_ok=True)

    # ===== Rollout =====
    for step in range(5):
        obs, _, _, _ = env.step([0.0] * 7)

        # Save rendered images
        for cam in camera_names:
            if f"{cam}_image" in obs:
                Image.fromarray(obs[f"{cam}_image"]).save(
                    f"gt_meshes/{cam}_step_{step}.png"
                )

        # Extract meshes
        meshes = collect_world_meshes(env)

        # Sample world point cloud
        world_pts = sample_points_from_meshes(meshes, pts_per_mesh=8000)

        # Camera projection for each view
        for cam in camera_names:
            cam_w = env._camera_widths[cam]
            cam_h = env._camera_heights[cam]

            cam_params = get_camera_params(
                env.sim, cam,
                cam_w,
                cam_h,
            )

            cam_pts = crop_points_by_camera(
                world_pts,
                cam_params,
                cam_w,
                cam_h
            )

            save_point_cloud_ply(
                cam_pts,
                f"gt_meshes/{cam}_step_{step}_pcd.ply"
            )

        print(f"[step {step}] saved point clouds.")

    env.close()


if __name__ == "__main__":
    main()
