import os
import math
import numpy as np
from PIL import Image

from libero.libero import benchmark, get_libero_path
from libero.libero.envs import OffScreenRenderEnv

# Mujoco geom type IDs (avoid explicit mujoco import)
GEOM_PLANE = 0
GEOM_HFIELD = 1
GEOM_SPHERE = 2
GEOM_CAPSULE = 3
GEOM_ELLIPSOID = 4
GEOM_CYLINDER = 5
GEOM_BOX = 6
GEOM_MESH = 7


def save_point_cloud_ply(points, path):
    header = "ply\nformat ascii 1.0\ncomment generated by export_gt_pointcloud.py\n"
    header += f"element vertex {len(points)}\n"
    header += "property float x\nproperty float y\nproperty float z\n"
    header += "end_header\n"
    with open(path, "w") as f:
        f.write(header)
        np.savetxt(f, points, fmt="%.6f")


def geom_mesh_in_world(sim, geom_id):
    """Return (verts_world, faces) for a mesh geom."""
    model, data = sim.model, sim.data
    mesh_id = model.geom_dataid[geom_id]
    if mesh_id < 0:
        return None
    v_adr = model.mesh_vertadr[mesh_id]
    v_num = model.mesh_vertnum[mesh_id]
    f_adr = model.mesh_faceadr[mesh_id]
    f_num = model.mesh_facenum[mesh_id]
    verts_local = model.mesh_vert[v_adr : v_adr + v_num]
    faces = model.mesh_face[f_adr : f_adr + f_num]
    R = data.geom_xmat[geom_id].reshape(3, 3)
    t = data.geom_xpos[geom_id]
    verts_world = verts_local @ R.T + t
    return verts_world, faces


def box_geom_in_world(sim, geom_id):
    """Approximate a box primitive as a mesh (8 verts, 12 faces)."""
    model, data = sim.model, sim.data
    hx, hy, hz = model.geom_size[geom_id]
    # 8 corners in geom frame
    corners = np.array(
        [
            [-hx, -hy, -hz],
            [-hx, -hy, hz],
            [-hx, hy, -hz],
            [-hx, hy, hz],
            [hx, -hy, -hz],
            [hx, -hy, hz],
            [hx, hy, -hz],
            [hx, hy, hz],
        ]
    )
    R = data.geom_xmat[geom_id].reshape(3, 3)
    t = data.geom_xpos[geom_id]
    verts_world = corners @ R.T + t
    faces = np.array(
        [
            [0, 1, 3],
            [0, 3, 2],
            [4, 6, 7],
            [4, 7, 5],
            [0, 4, 5],
            [0, 5, 1],
            [2, 3, 7],
            [2, 7, 6],
            [0, 2, 6],
            [0, 6, 4],
            [1, 5, 7],
            [1, 7, 3],
        ],
        dtype=np.int32,
    )
    return verts_world, faces


def collect_world_meshes(
    env,
    include_robot=True,
    include_statics=True,
    exclude_body_substrings=(),
):
    """Collect per-geom meshes in world frame."""
    sim, model = env.sim, env.sim.model
    meshes = []
    for geom_id in range(model.ngeom):
        body_id = model.geom_bodyid[geom_id]
        body_name = model.body_id2name(body_id) or f"body_{body_id}"
        lname = body_name.lower()
        if not include_robot and ("panda" in lname or "robot" in lname or "gripper" in lname):
            continue
        is_static = body_id == 0 or "floor" in lname or "table" in lname or "ground" in lname
        if not include_statics and is_static:
            continue
        if exclude_body_substrings and any(substr.lower() in lname for substr in exclude_body_substrings):
            continue
        geom_type = model.geom_type[geom_id]
        if geom_type == GEOM_MESH:
            mesh = geom_mesh_in_world(sim, geom_id)
        elif geom_type == GEOM_BOX:
            mesh = box_geom_in_world(sim, geom_id)
        else:
            mesh = None
        if mesh is None:
            continue
        verts_world, faces = mesh
        meshes.append(
            {
                "name": f"{body_name}_geom{geom_id}",
                "verts": verts_world,
                "faces": faces,
            }
        )
    return meshes


def get_reference_center(meshes, keyword="table"):
    """Estimate center of the first mesh whose name contains keyword."""
    for m in meshes:
        if keyword in m["name"].lower():
            verts = m["verts"]
            if len(verts) > 0:
                return verts.mean(axis=0)
    return np.zeros(3)


def center_and_crop_meshes(meshes, ref_center, cube_half):
    """Shift meshes by ref_center and drop triangles outside the cube."""
    centered = []
    bounds = np.array([cube_half, cube_half, cube_half])
    for m in meshes:
        verts = m["verts"] - ref_center
        faces = m["faces"]
        if len(verts) == 0 or len(faces) == 0:
            continue
        tri = verts[faces]  # (F,3,3)
        if tri.ndim != 3 or tri.shape[1] != 3:
            continue
        tri_min = tri.min(axis=1)
        tri_max = tri.max(axis=1)
        overlap = (
            (tri_min[:, 0] <= bounds[0]) & (tri_max[:, 0] >= -bounds[0])
            & (tri_min[:, 1] <= bounds[1]) & (tri_max[:, 1] >= -bounds[1])
            & (tri_min[:, 2] <= bounds[2]) & (tri_max[:, 2] >= -bounds[2])
        )
        faces_filtered = faces[overlap]
        if len(faces_filtered) == 0:
            continue
        centered.append(
            {
                "name": m["name"],
                "verts": verts,
                "faces": faces_filtered,
            }
        )
    return centered


def save_meshes_as_obj(meshes, path):
    """Write combined OBJ with per-geom objects."""
    with open(path, "w") as f:
        f.write("# Generated by export_gt_pointcloud.py\n")
        vert_offset = 0
        for mesh in meshes:
            name = mesh["name"].replace(" ", "_")
            verts = mesh["verts"]
            faces = mesh["faces"]
            f.write(f"o {name}\n")
            np.savetxt(f, verts, fmt="v %.6f %.6f %.6f")
            # OBJ is 1-indexed; faces are triangles
            faces_shifted = faces + vert_offset + 1
            np.savetxt(f, faces_shifted, fmt="f %d %d %d")
            vert_offset += verts.shape[0]


def get_camera_params(sim, camera_name, width, height):
    cam_id = sim.model.camera_name2id(camera_name)
    fovy = sim.model.cam_fovy[cam_id]
    fy = 0.5 * height / math.tan(np.deg2rad(fovy) / 2.0)
    fx = fy * width / height
    cx = (width - 1) / 2.0
    cy = (height - 1) / 2.0
    R = sim.data.cam_xmat[cam_id].reshape(3, 3)
    t = sim.data.cam_xpos[cam_id]
    return {"fx": fx, "fy": fy, "cx": cx, "cy": cy, "R": R, "t": t, "fovy": fovy}


def save_camera_info(camera_params, path):
    with open(path, "w") as f:
        for cam, params in camera_params.items():
            f.write(f"[{cam}]\n")
            f.write(f"fx={params['fx']:.6f} fy={params['fy']:.6f} cx={params['cx']:.6f} cy={params['cy']:.6f} fovy={params['fovy']:.6f}\n")
            R = params["R"]
            t = params["t"]
            f.write("R=\n")
            np.savetxt(f, R, fmt="%.6f")
            f.write("t=\n")
            np.savetxt(f, t.reshape(1, -1), fmt="%.6f")
        f.write("\n")


def sample_points_on_mesh(verts, faces, n_samples):
    """Sample points uniformly on a mesh using face areas."""
    if len(faces) == 0 or len(verts) == 0 or n_samples <= 0:
        return np.zeros((0, 3))
    tri = verts[faces]  # (F, 3, 3)
    areas = 0.5 * np.linalg.norm(np.cross(tri[:, 1] - tri[:, 0], tri[:, 2] - tri[:, 0]), axis=1)
    total = areas.sum()
    if total <= 1e-9:
        return np.zeros((0, 3))
    probs = areas / total
    face_idx = np.random.choice(len(faces), size=n_samples, p=probs)
    tri_sel = tri[face_idx]
    r1 = np.sqrt(np.random.rand(n_samples, 1))
    r2 = np.random.rand(n_samples, 1)
    samples = tri_sel[:, 0] + r1 * (tri_sel[:, 1] - tri_sel[:, 0]) + r2 * (tri_sel[:, 2] - tri_sel[:, 0])
    return samples


def _allocate_counts_by_area(meshes, total_points, min_per_mesh):
    areas = []
    for m in meshes:
        tri = m["verts"][m["faces"]] if len(m["faces"]) > 0 else np.zeros((0, 3, 3))
        if len(tri) == 0:
            areas.append(0.0)
        else:
            a = 0.5 * np.linalg.norm(np.cross(tri[:, 1] - tri[:, 0], tri[:, 2] - tri[:, 0]), axis=1).sum()
            areas.append(float(a))
    areas = np.array(areas)
    if areas.sum() <= 1e-9:
        return [min_per_mesh] * len(meshes)
    weights = areas / areas.sum()
    counts = np.floor(weights * total_points).astype(int)
    counts = np.maximum(counts, min_per_mesh)
    diff = total_points - counts.sum()
    if diff > 0:
        order = np.argsort(-weights)
        for i in range(diff):
            counts[order[i % len(order)]] += 1
    elif diff < 0:
        order = np.argsort(weights)
        i = 0
        while diff < 0 and i < len(order):
            idx = order[i]
            if counts[idx] > min_per_mesh:
                counts[idx] -= 1
                diff += 1
            else:
                i += 1
    return counts.tolist()


def sample_points_from_meshes(meshes, total_points, min_per_mesh=200):
    """Sample a total number of points across meshes proportional to their surface area."""
    if not meshes or total_points <= 0:
        return np.zeros((0, 3))
    counts = _allocate_counts_by_area(meshes, total_points, min_per_mesh)
    pts = []
    for m, c in zip(meshes, counts):
        pts.append(sample_points_on_mesh(m["verts"], m["faces"], c))
    return np.concatenate(pts, axis=0) if pts else np.zeros((0, 3))


def main():
    benchmark_dict = benchmark.get_benchmark_dict()
    task_suite_name = "libero_spatial"
    task_id = 0
    task_suite = benchmark_dict[task_suite_name]()
    task = task_suite.get_task(task_id)
    task_bddl_file = os.path.join(
        get_libero_path("bddl_files"), task.problem_folder, task.bddl_file
    )

    camera_names = ["agentview", "robot0_eye_in_hand"]
    env_args = {
        "bddl_file_name": task_bddl_file,
        "camera_heights": 128,
        "camera_widths": 128,
        "camera_names": camera_names,
        "camera_depths": False,  # using meshes directly
    }
    env = OffScreenRenderEnv(**env_args)
    env.seed(0)
    env.reset()
    init_states = task_suite.get_task_init_states(task_id)
    env.set_init_state(init_states[0])

    os.makedirs("gt_meshes", exist_ok=True)
    dummy_action = [0.0] * 7
    total_mesh_samples = 200000  # total points to sample across meshes before cropping
    min_samples_per_mesh = 200

    for step in range(5):
        obs, reward, done, info = env.step(dummy_action)

        # Save reference images
        for cam in camera_names:
            img_key = f"{cam}_image"
            if img_key in obs:
                Image.fromarray(obs[img_key]).save(
                    os.path.join("gt_meshes", f"{cam}_step_{step}.png")
                )

        # Collect meshes in world frame to match rendered frame
        meshes = collect_world_meshes(
            env,
            include_robot=True,
            include_statics=True,
            exclude_body_substrings=(),
        )
        obj_path = os.path.join("gt_meshes", f"scene_step_{step}.obj")
        save_meshes_as_obj(meshes, obj_path)

        # Camera parameters for reproducing the exact render viewpoint
        cam_info = {}
        for cam in camera_names:
            h, w = env_args["camera_heights"], env_args["camera_widths"]
            cam_info[cam] = get_camera_params(env.sim, cam, w, h)
        cam_info_path = os.path.join("gt_meshes", f"cameras_step_{step}.txt")
        save_camera_info(cam_info, cam_info_path)

        # Translate so that table center sits at origin, then cube-crop meshes in that frame
        ref_center = get_reference_center(meshes, keyword="table")
        cube_half = 0.5  # meters; adjust as needed
        centered_meshes = center_and_crop_meshes(meshes, ref_center, cube_half)
        cube_obj_path = os.path.join("gt_meshes", f"cube_step_{step}.obj")
        save_meshes_as_obj(centered_meshes, cube_obj_path)

        print(
            f"[step {step}] reward={reward:.3f} done={done} saved meshes -> {obj_path}, cube -> {cube_obj_path}"
        )

    env.close()


if __name__ == "__main__":
    main()
