from libero.libero import benchmark
from libero.libero import get_libero_path
from libero.libero.envs import SegmentationRenderEnv
import os
import numpy as np
from PIL import Image
import math


def depth_buffer_to_meters(depth_buffer, near, far):
    depth_buffer = np.squeeze(depth_buffer)
    if depth_buffer.max() <= 1.0 + 1e-6:
        return (near * far) / (far - (far - near) * depth_buffer)
    return depth_buffer


def depth_to_point_cloud(depth_m, fx, fy, cx, cy):
    h, w = depth_m.shape
    i_coords, j_coords = np.indices((h, w))
    z = depth_m
    x = (j_coords - cx) * z / fx
    y = (i_coords - cy) * z / fy
    points = np.stack((x, y, z), axis=-1).reshape(-1, 3)
    mask = np.isfinite(points).all(axis=1)
    return points[mask]


def save_point_cloud_ply(points, path):
    header = "ply\nformat ascii 1.0\ncomment generated by sample.py\n"
    header += f"element vertex {len(points)}\n"
    header += "property float x\nproperty float y\nproperty float z\n"
    header += "end_header\n"
    with open(path, "w") as f:
        f.write(header)
        np.savetxt(f, points, fmt="%.6f")


def get_camera_intrinsics(env, camera_name, width, height):
    cam_id = env.sim.model.camera_name2id(camera_name)
    fovy = env.sim.model.cam_fovy[cam_id]
    fy = 0.5 * height / math.tan(np.deg2rad(fovy) / 2.0)
    fx = fy * width / height
    cx = (width - 1) / 2.0
    cy = (height - 1) / 2.0
    return fx, fy, cx, cy


def extract_segmentation(obs, cam_name):
    for key in (f"{cam_name}_segmentation", f"{cam_name}_seg"):
        if key in obs:
            seg = np.squeeze(obs[key])
            if seg.ndim == 3:
                seg = seg[..., 0]
            return seg
    return None


def downsample_points(points, max_points):
    if max_points is None or len(points) <= max_points:
        return points
    idx = np.random.choice(len(points), size=max_points, replace=False)
    return points[idx]


benchmark_dict = benchmark.get_benchmark_dict()
task_suite_name = "libero_spatial" # can also choose libero_spatial, libero_object, etc.
task_suite = benchmark_dict[task_suite_name]()

# retrieve a specific task
task_id = 0
task = task_suite.get_task(task_id)
task_name = task.name
task_description = task.language
task_bddl_file = os.path.join(get_libero_path("bddl_files"), task.problem_folder, task.bddl_file)
print(f"[info] retrieving task {task_id} from suite {task_suite_name}, the " + \
      f"language instruction is {task_description}, and the bddl file is {task_bddl_file}")

# step over the environment
camera_names = ["agentview", "robot0_eye_in_hand"]
max_points_per_cloud = None  # set to None to keep all points
env_args = {
    "bddl_file_name": task_bddl_file,
    "camera_heights": 128,
    "camera_widths": 128,
    "camera_names": camera_names,
    "camera_depths": True,
    "camera_segmentations": "instance",  # needed to drop background
}
env = SegmentationRenderEnv(**env_args)
env.seed(0)
env.reset()
init_states = task_suite.get_task_init_states(task_id) # for benchmarking purpose, we fix the a set of initial states
init_state_id = 0
env.set_init_state(init_states[init_state_id])

dummy_action = [0.] * 7
os.makedirs("pointclouds", exist_ok=True)

print("\n[info] Running 10 steps with dummy actions...")
for step in range(10):
    obs, reward, done, info = env.step(dummy_action)
    print(f"Step {step}: reward={reward:.4f}, done={done}")
    print(f"  Observation keys: {obs.keys()}")
    print(f"  Info: {info}")
    
    # Save images from camera observations
    if 'agentview_image' in obs:
        img = Image.fromarray(obs['agentview_image'])
        img.save(f'step_{step}.png')
        print(f"  Saved image to step_{step}.png")

    # Extract and save point clouds from depth maps
    near, far = env.sim.model.vis.map.znear, env.sim.model.vis.map.zfar
    for cam_name in camera_names:
        depth_key = f"{cam_name}_depth"
        if depth_key not in obs:
            continue
        depth_buffer = obs[depth_key]
        depth_m = depth_buffer_to_meters(depth_buffer, near, far)
        seg = extract_segmentation(obs, cam_name)
        if seg is not None:
            depth_m = np.where(seg > 0, depth_m, np.nan)
        h, w = depth_m.shape
        fx, fy, cx, cy = get_camera_intrinsics(env, cam_name, w, h)
        points = depth_to_point_cloud(depth_m, fx, fy, cx, cy)
        points = downsample_points(points, max_points_per_cloud)
        ply_path = os.path.join("pointclouds", f"{cam_name}_step_{step}.ply")
        save_point_cloud_ply(points, ply_path)
        print(f"  Saved {len(points)} pts to {ply_path}")

env.close()
print("\n[info] Done!")
